// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: speechly/slu/v1/wlu.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_speechly_2fslu_2fv1_2fwlu_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_speechly_2fslu_2fv1_2fwlu_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3008000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3008000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/timestamp.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_speechly_2fslu_2fv1_2fwlu_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_speechly_2fslu_2fv1_2fwlu_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[8]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_speechly_2fslu_2fv1_2fwlu_2eproto;
namespace speechly {
namespace slu {
namespace v1 {
class TextsRequest;
class TextsRequestDefaultTypeInternal;
extern TextsRequestDefaultTypeInternal _TextsRequest_default_instance_;
class TextsResponse;
class TextsResponseDefaultTypeInternal;
extern TextsResponseDefaultTypeInternal _TextsResponse_default_instance_;
class WLUEntity;
class WLUEntityDefaultTypeInternal;
extern WLUEntityDefaultTypeInternal _WLUEntity_default_instance_;
class WLUIntent;
class WLUIntentDefaultTypeInternal;
extern WLUIntentDefaultTypeInternal _WLUIntent_default_instance_;
class WLURequest;
class WLURequestDefaultTypeInternal;
extern WLURequestDefaultTypeInternal _WLURequest_default_instance_;
class WLUResponse;
class WLUResponseDefaultTypeInternal;
extern WLUResponseDefaultTypeInternal _WLUResponse_default_instance_;
class WLUSegment;
class WLUSegmentDefaultTypeInternal;
extern WLUSegmentDefaultTypeInternal _WLUSegment_default_instance_;
class WLUToken;
class WLUTokenDefaultTypeInternal;
extern WLUTokenDefaultTypeInternal _WLUToken_default_instance_;
}  // namespace v1
}  // namespace slu
}  // namespace speechly
PROTOBUF_NAMESPACE_OPEN
template<> ::speechly::slu::v1::TextsRequest* Arena::CreateMaybeMessage<::speechly::slu::v1::TextsRequest>(Arena*);
template<> ::speechly::slu::v1::TextsResponse* Arena::CreateMaybeMessage<::speechly::slu::v1::TextsResponse>(Arena*);
template<> ::speechly::slu::v1::WLUEntity* Arena::CreateMaybeMessage<::speechly::slu::v1::WLUEntity>(Arena*);
template<> ::speechly::slu::v1::WLUIntent* Arena::CreateMaybeMessage<::speechly::slu::v1::WLUIntent>(Arena*);
template<> ::speechly::slu::v1::WLURequest* Arena::CreateMaybeMessage<::speechly::slu::v1::WLURequest>(Arena*);
template<> ::speechly::slu::v1::WLUResponse* Arena::CreateMaybeMessage<::speechly::slu::v1::WLUResponse>(Arena*);
template<> ::speechly::slu::v1::WLUSegment* Arena::CreateMaybeMessage<::speechly::slu::v1::WLUSegment>(Arena*);
template<> ::speechly::slu::v1::WLUToken* Arena::CreateMaybeMessage<::speechly::slu::v1::WLUToken>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace speechly {
namespace slu {
namespace v1 {

// ===================================================================

class TextsRequest :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:speechly.slu.v1.TextsRequest) */ {
 public:
  TextsRequest();
  virtual ~TextsRequest();

  TextsRequest(const TextsRequest& from);
  TextsRequest(TextsRequest&& from) noexcept
    : TextsRequest() {
    *this = ::std::move(from);
  }

  inline TextsRequest& operator=(const TextsRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline TextsRequest& operator=(TextsRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TextsRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TextsRequest* internal_default_instance() {
    return reinterpret_cast<const TextsRequest*>(
               &_TextsRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(TextsRequest* other);
  friend void swap(TextsRequest& a, TextsRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TextsRequest* New() const final {
    return CreateMaybeMessage<TextsRequest>(nullptr);
  }

  TextsRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TextsRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TextsRequest& from);
  void MergeFrom(const TextsRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TextsRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "speechly.slu.v1.TextsRequest";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_speechly_2fslu_2fv1_2fwlu_2eproto);
    return ::descriptor_table_speechly_2fslu_2fv1_2fwlu_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .speechly.slu.v1.WLURequest requests = 2;
  int requests_size() const;
  void clear_requests();
  static const int kRequestsFieldNumber = 2;
  ::speechly::slu::v1::WLURequest* mutable_requests(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLURequest >*
      mutable_requests();
  const ::speechly::slu::v1::WLURequest& requests(int index) const;
  ::speechly::slu::v1::WLURequest* add_requests();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLURequest >&
      requests() const;

  // string app_id = 1;
  void clear_app_id();
  static const int kAppIdFieldNumber = 1;
  const std::string& app_id() const;
  void set_app_id(const std::string& value);
  void set_app_id(std::string&& value);
  void set_app_id(const char* value);
  void set_app_id(const char* value, size_t size);
  std::string* mutable_app_id();
  std::string* release_app_id();
  void set_allocated_app_id(std::string* app_id);

  // @@protoc_insertion_point(class_scope:speechly.slu.v1.TextsRequest)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLURequest > requests_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr app_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_speechly_2fslu_2fv1_2fwlu_2eproto;
};
// -------------------------------------------------------------------

class TextsResponse :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:speechly.slu.v1.TextsResponse) */ {
 public:
  TextsResponse();
  virtual ~TextsResponse();

  TextsResponse(const TextsResponse& from);
  TextsResponse(TextsResponse&& from) noexcept
    : TextsResponse() {
    *this = ::std::move(from);
  }

  inline TextsResponse& operator=(const TextsResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline TextsResponse& operator=(TextsResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TextsResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TextsResponse* internal_default_instance() {
    return reinterpret_cast<const TextsResponse*>(
               &_TextsResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(TextsResponse* other);
  friend void swap(TextsResponse& a, TextsResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TextsResponse* New() const final {
    return CreateMaybeMessage<TextsResponse>(nullptr);
  }

  TextsResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TextsResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TextsResponse& from);
  void MergeFrom(const TextsResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TextsResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "speechly.slu.v1.TextsResponse";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_speechly_2fslu_2fv1_2fwlu_2eproto);
    return ::descriptor_table_speechly_2fslu_2fv1_2fwlu_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .speechly.slu.v1.WLUResponse responses = 1;
  int responses_size() const;
  void clear_responses();
  static const int kResponsesFieldNumber = 1;
  ::speechly::slu::v1::WLUResponse* mutable_responses(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLUResponse >*
      mutable_responses();
  const ::speechly::slu::v1::WLUResponse& responses(int index) const;
  ::speechly::slu::v1::WLUResponse* add_responses();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLUResponse >&
      responses() const;

  // @@protoc_insertion_point(class_scope:speechly.slu.v1.TextsResponse)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLUResponse > responses_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_speechly_2fslu_2fv1_2fwlu_2eproto;
};
// -------------------------------------------------------------------

class WLURequest :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:speechly.slu.v1.WLURequest) */ {
 public:
  WLURequest();
  virtual ~WLURequest();

  WLURequest(const WLURequest& from);
  WLURequest(WLURequest&& from) noexcept
    : WLURequest() {
    *this = ::std::move(from);
  }

  inline WLURequest& operator=(const WLURequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline WLURequest& operator=(WLURequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const WLURequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const WLURequest* internal_default_instance() {
    return reinterpret_cast<const WLURequest*>(
               &_WLURequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(WLURequest* other);
  friend void swap(WLURequest& a, WLURequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline WLURequest* New() const final {
    return CreateMaybeMessage<WLURequest>(nullptr);
  }

  WLURequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<WLURequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const WLURequest& from);
  void MergeFrom(const WLURequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WLURequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "speechly.slu.v1.WLURequest";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_speechly_2fslu_2fv1_2fwlu_2eproto);
    return ::descriptor_table_speechly_2fslu_2fv1_2fwlu_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string language_code = 1;
  void clear_language_code();
  static const int kLanguageCodeFieldNumber = 1;
  const std::string& language_code() const;
  void set_language_code(const std::string& value);
  void set_language_code(std::string&& value);
  void set_language_code(const char* value);
  void set_language_code(const char* value, size_t size);
  std::string* mutable_language_code();
  std::string* release_language_code();
  void set_allocated_language_code(std::string* language_code);

  // string text = 2;
  void clear_text();
  static const int kTextFieldNumber = 2;
  const std::string& text() const;
  void set_text(const std::string& value);
  void set_text(std::string&& value);
  void set_text(const char* value);
  void set_text(const char* value, size_t size);
  std::string* mutable_text();
  std::string* release_text();
  void set_allocated_text(std::string* text);

  // .google.protobuf.Timestamp reference_time = 3;
  bool has_reference_time() const;
  void clear_reference_time();
  static const int kReferenceTimeFieldNumber = 3;
  const PROTOBUF_NAMESPACE_ID::Timestamp& reference_time() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* release_reference_time();
  PROTOBUF_NAMESPACE_ID::Timestamp* mutable_reference_time();
  void set_allocated_reference_time(PROTOBUF_NAMESPACE_ID::Timestamp* reference_time);

  // @@protoc_insertion_point(class_scope:speechly.slu.v1.WLURequest)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr language_code_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr text_;
  PROTOBUF_NAMESPACE_ID::Timestamp* reference_time_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_speechly_2fslu_2fv1_2fwlu_2eproto;
};
// -------------------------------------------------------------------

class WLUResponse :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:speechly.slu.v1.WLUResponse) */ {
 public:
  WLUResponse();
  virtual ~WLUResponse();

  WLUResponse(const WLUResponse& from);
  WLUResponse(WLUResponse&& from) noexcept
    : WLUResponse() {
    *this = ::std::move(from);
  }

  inline WLUResponse& operator=(const WLUResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline WLUResponse& operator=(WLUResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const WLUResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const WLUResponse* internal_default_instance() {
    return reinterpret_cast<const WLUResponse*>(
               &_WLUResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(WLUResponse* other);
  friend void swap(WLUResponse& a, WLUResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline WLUResponse* New() const final {
    return CreateMaybeMessage<WLUResponse>(nullptr);
  }

  WLUResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<WLUResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const WLUResponse& from);
  void MergeFrom(const WLUResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WLUResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "speechly.slu.v1.WLUResponse";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_speechly_2fslu_2fv1_2fwlu_2eproto);
    return ::descriptor_table_speechly_2fslu_2fv1_2fwlu_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .speechly.slu.v1.WLUSegment segments = 1;
  int segments_size() const;
  void clear_segments();
  static const int kSegmentsFieldNumber = 1;
  ::speechly::slu::v1::WLUSegment* mutable_segments(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLUSegment >*
      mutable_segments();
  const ::speechly::slu::v1::WLUSegment& segments(int index) const;
  ::speechly::slu::v1::WLUSegment* add_segments();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLUSegment >&
      segments() const;

  // @@protoc_insertion_point(class_scope:speechly.slu.v1.WLUResponse)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLUSegment > segments_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_speechly_2fslu_2fv1_2fwlu_2eproto;
};
// -------------------------------------------------------------------

class WLUSegment :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:speechly.slu.v1.WLUSegment) */ {
 public:
  WLUSegment();
  virtual ~WLUSegment();

  WLUSegment(const WLUSegment& from);
  WLUSegment(WLUSegment&& from) noexcept
    : WLUSegment() {
    *this = ::std::move(from);
  }

  inline WLUSegment& operator=(const WLUSegment& from) {
    CopyFrom(from);
    return *this;
  }
  inline WLUSegment& operator=(WLUSegment&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const WLUSegment& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const WLUSegment* internal_default_instance() {
    return reinterpret_cast<const WLUSegment*>(
               &_WLUSegment_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(WLUSegment* other);
  friend void swap(WLUSegment& a, WLUSegment& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline WLUSegment* New() const final {
    return CreateMaybeMessage<WLUSegment>(nullptr);
  }

  WLUSegment* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<WLUSegment>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const WLUSegment& from);
  void MergeFrom(const WLUSegment& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WLUSegment* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "speechly.slu.v1.WLUSegment";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_speechly_2fslu_2fv1_2fwlu_2eproto);
    return ::descriptor_table_speechly_2fslu_2fv1_2fwlu_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .speechly.slu.v1.WLUToken tokens = 2;
  int tokens_size() const;
  void clear_tokens();
  static const int kTokensFieldNumber = 2;
  ::speechly::slu::v1::WLUToken* mutable_tokens(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLUToken >*
      mutable_tokens();
  const ::speechly::slu::v1::WLUToken& tokens(int index) const;
  ::speechly::slu::v1::WLUToken* add_tokens();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLUToken >&
      tokens() const;

  // repeated .speechly.slu.v1.WLUEntity entities = 3;
  int entities_size() const;
  void clear_entities();
  static const int kEntitiesFieldNumber = 3;
  ::speechly::slu::v1::WLUEntity* mutable_entities(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLUEntity >*
      mutable_entities();
  const ::speechly::slu::v1::WLUEntity& entities(int index) const;
  ::speechly::slu::v1::WLUEntity* add_entities();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLUEntity >&
      entities() const;

  // string text = 1;
  void clear_text();
  static const int kTextFieldNumber = 1;
  const std::string& text() const;
  void set_text(const std::string& value);
  void set_text(std::string&& value);
  void set_text(const char* value);
  void set_text(const char* value, size_t size);
  std::string* mutable_text();
  std::string* release_text();
  void set_allocated_text(std::string* text);

  // string annotated_text = 5;
  void clear_annotated_text();
  static const int kAnnotatedTextFieldNumber = 5;
  const std::string& annotated_text() const;
  void set_annotated_text(const std::string& value);
  void set_annotated_text(std::string&& value);
  void set_annotated_text(const char* value);
  void set_annotated_text(const char* value, size_t size);
  std::string* mutable_annotated_text();
  std::string* release_annotated_text();
  void set_allocated_annotated_text(std::string* annotated_text);

  // .speechly.slu.v1.WLUIntent intent = 4;
  bool has_intent() const;
  void clear_intent();
  static const int kIntentFieldNumber = 4;
  const ::speechly::slu::v1::WLUIntent& intent() const;
  ::speechly::slu::v1::WLUIntent* release_intent();
  ::speechly::slu::v1::WLUIntent* mutable_intent();
  void set_allocated_intent(::speechly::slu::v1::WLUIntent* intent);

  // @@protoc_insertion_point(class_scope:speechly.slu.v1.WLUSegment)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLUToken > tokens_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLUEntity > entities_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr text_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr annotated_text_;
  ::speechly::slu::v1::WLUIntent* intent_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_speechly_2fslu_2fv1_2fwlu_2eproto;
};
// -------------------------------------------------------------------

class WLUToken :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:speechly.slu.v1.WLUToken) */ {
 public:
  WLUToken();
  virtual ~WLUToken();

  WLUToken(const WLUToken& from);
  WLUToken(WLUToken&& from) noexcept
    : WLUToken() {
    *this = ::std::move(from);
  }

  inline WLUToken& operator=(const WLUToken& from) {
    CopyFrom(from);
    return *this;
  }
  inline WLUToken& operator=(WLUToken&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const WLUToken& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const WLUToken* internal_default_instance() {
    return reinterpret_cast<const WLUToken*>(
               &_WLUToken_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(WLUToken* other);
  friend void swap(WLUToken& a, WLUToken& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline WLUToken* New() const final {
    return CreateMaybeMessage<WLUToken>(nullptr);
  }

  WLUToken* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<WLUToken>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const WLUToken& from);
  void MergeFrom(const WLUToken& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WLUToken* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "speechly.slu.v1.WLUToken";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_speechly_2fslu_2fv1_2fwlu_2eproto);
    return ::descriptor_table_speechly_2fslu_2fv1_2fwlu_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string word = 1;
  void clear_word();
  static const int kWordFieldNumber = 1;
  const std::string& word() const;
  void set_word(const std::string& value);
  void set_word(std::string&& value);
  void set_word(const char* value);
  void set_word(const char* value, size_t size);
  std::string* mutable_word();
  std::string* release_word();
  void set_allocated_word(std::string* word);

  // int32 index = 2;
  void clear_index();
  static const int kIndexFieldNumber = 2;
  ::PROTOBUF_NAMESPACE_ID::int32 index() const;
  void set_index(::PROTOBUF_NAMESPACE_ID::int32 value);

  // @@protoc_insertion_point(class_scope:speechly.slu.v1.WLUToken)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr word_;
  ::PROTOBUF_NAMESPACE_ID::int32 index_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_speechly_2fslu_2fv1_2fwlu_2eproto;
};
// -------------------------------------------------------------------

class WLUEntity :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:speechly.slu.v1.WLUEntity) */ {
 public:
  WLUEntity();
  virtual ~WLUEntity();

  WLUEntity(const WLUEntity& from);
  WLUEntity(WLUEntity&& from) noexcept
    : WLUEntity() {
    *this = ::std::move(from);
  }

  inline WLUEntity& operator=(const WLUEntity& from) {
    CopyFrom(from);
    return *this;
  }
  inline WLUEntity& operator=(WLUEntity&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const WLUEntity& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const WLUEntity* internal_default_instance() {
    return reinterpret_cast<const WLUEntity*>(
               &_WLUEntity_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(WLUEntity* other);
  friend void swap(WLUEntity& a, WLUEntity& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline WLUEntity* New() const final {
    return CreateMaybeMessage<WLUEntity>(nullptr);
  }

  WLUEntity* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<WLUEntity>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const WLUEntity& from);
  void MergeFrom(const WLUEntity& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WLUEntity* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "speechly.slu.v1.WLUEntity";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_speechly_2fslu_2fv1_2fwlu_2eproto);
    return ::descriptor_table_speechly_2fslu_2fv1_2fwlu_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string entity = 1;
  void clear_entity();
  static const int kEntityFieldNumber = 1;
  const std::string& entity() const;
  void set_entity(const std::string& value);
  void set_entity(std::string&& value);
  void set_entity(const char* value);
  void set_entity(const char* value, size_t size);
  std::string* mutable_entity();
  std::string* release_entity();
  void set_allocated_entity(std::string* entity);

  // string value = 2;
  void clear_value();
  static const int kValueFieldNumber = 2;
  const std::string& value() const;
  void set_value(const std::string& value);
  void set_value(std::string&& value);
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  std::string* mutable_value();
  std::string* release_value();
  void set_allocated_value(std::string* value);

  // int32 start_position = 3;
  void clear_start_position();
  static const int kStartPositionFieldNumber = 3;
  ::PROTOBUF_NAMESPACE_ID::int32 start_position() const;
  void set_start_position(::PROTOBUF_NAMESPACE_ID::int32 value);

  // int32 end_position = 4;
  void clear_end_position();
  static const int kEndPositionFieldNumber = 4;
  ::PROTOBUF_NAMESPACE_ID::int32 end_position() const;
  void set_end_position(::PROTOBUF_NAMESPACE_ID::int32 value);

  // @@protoc_insertion_point(class_scope:speechly.slu.v1.WLUEntity)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr entity_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr value_;
  ::PROTOBUF_NAMESPACE_ID::int32 start_position_;
  ::PROTOBUF_NAMESPACE_ID::int32 end_position_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_speechly_2fslu_2fv1_2fwlu_2eproto;
};
// -------------------------------------------------------------------

class WLUIntent :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:speechly.slu.v1.WLUIntent) */ {
 public:
  WLUIntent();
  virtual ~WLUIntent();

  WLUIntent(const WLUIntent& from);
  WLUIntent(WLUIntent&& from) noexcept
    : WLUIntent() {
    *this = ::std::move(from);
  }

  inline WLUIntent& operator=(const WLUIntent& from) {
    CopyFrom(from);
    return *this;
  }
  inline WLUIntent& operator=(WLUIntent&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const WLUIntent& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const WLUIntent* internal_default_instance() {
    return reinterpret_cast<const WLUIntent*>(
               &_WLUIntent_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  void Swap(WLUIntent* other);
  friend void swap(WLUIntent& a, WLUIntent& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline WLUIntent* New() const final {
    return CreateMaybeMessage<WLUIntent>(nullptr);
  }

  WLUIntent* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<WLUIntent>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const WLUIntent& from);
  void MergeFrom(const WLUIntent& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(WLUIntent* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "speechly.slu.v1.WLUIntent";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_speechly_2fslu_2fv1_2fwlu_2eproto);
    return ::descriptor_table_speechly_2fslu_2fv1_2fwlu_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string intent = 1;
  void clear_intent();
  static const int kIntentFieldNumber = 1;
  const std::string& intent() const;
  void set_intent(const std::string& value);
  void set_intent(std::string&& value);
  void set_intent(const char* value);
  void set_intent(const char* value, size_t size);
  std::string* mutable_intent();
  std::string* release_intent();
  void set_allocated_intent(std::string* intent);

  // @@protoc_insertion_point(class_scope:speechly.slu.v1.WLUIntent)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr intent_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_speechly_2fslu_2fv1_2fwlu_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TextsRequest

// string app_id = 1;
inline void TextsRequest::clear_app_id() {
  app_id_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& TextsRequest::app_id() const {
  // @@protoc_insertion_point(field_get:speechly.slu.v1.TextsRequest.app_id)
  return app_id_.GetNoArena();
}
inline void TextsRequest::set_app_id(const std::string& value) {
  
  app_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:speechly.slu.v1.TextsRequest.app_id)
}
inline void TextsRequest::set_app_id(std::string&& value) {
  
  app_id_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:speechly.slu.v1.TextsRequest.app_id)
}
inline void TextsRequest::set_app_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  app_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:speechly.slu.v1.TextsRequest.app_id)
}
inline void TextsRequest::set_app_id(const char* value, size_t size) {
  
  app_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:speechly.slu.v1.TextsRequest.app_id)
}
inline std::string* TextsRequest::mutable_app_id() {
  
  // @@protoc_insertion_point(field_mutable:speechly.slu.v1.TextsRequest.app_id)
  return app_id_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* TextsRequest::release_app_id() {
  // @@protoc_insertion_point(field_release:speechly.slu.v1.TextsRequest.app_id)
  
  return app_id_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void TextsRequest::set_allocated_app_id(std::string* app_id) {
  if (app_id != nullptr) {
    
  } else {
    
  }
  app_id_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), app_id);
  // @@protoc_insertion_point(field_set_allocated:speechly.slu.v1.TextsRequest.app_id)
}

// repeated .speechly.slu.v1.WLURequest requests = 2;
inline int TextsRequest::requests_size() const {
  return requests_.size();
}
inline void TextsRequest::clear_requests() {
  requests_.Clear();
}
inline ::speechly::slu::v1::WLURequest* TextsRequest::mutable_requests(int index) {
  // @@protoc_insertion_point(field_mutable:speechly.slu.v1.TextsRequest.requests)
  return requests_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLURequest >*
TextsRequest::mutable_requests() {
  // @@protoc_insertion_point(field_mutable_list:speechly.slu.v1.TextsRequest.requests)
  return &requests_;
}
inline const ::speechly::slu::v1::WLURequest& TextsRequest::requests(int index) const {
  // @@protoc_insertion_point(field_get:speechly.slu.v1.TextsRequest.requests)
  return requests_.Get(index);
}
inline ::speechly::slu::v1::WLURequest* TextsRequest::add_requests() {
  // @@protoc_insertion_point(field_add:speechly.slu.v1.TextsRequest.requests)
  return requests_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLURequest >&
TextsRequest::requests() const {
  // @@protoc_insertion_point(field_list:speechly.slu.v1.TextsRequest.requests)
  return requests_;
}

// -------------------------------------------------------------------

// TextsResponse

// repeated .speechly.slu.v1.WLUResponse responses = 1;
inline int TextsResponse::responses_size() const {
  return responses_.size();
}
inline void TextsResponse::clear_responses() {
  responses_.Clear();
}
inline ::speechly::slu::v1::WLUResponse* TextsResponse::mutable_responses(int index) {
  // @@protoc_insertion_point(field_mutable:speechly.slu.v1.TextsResponse.responses)
  return responses_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLUResponse >*
TextsResponse::mutable_responses() {
  // @@protoc_insertion_point(field_mutable_list:speechly.slu.v1.TextsResponse.responses)
  return &responses_;
}
inline const ::speechly::slu::v1::WLUResponse& TextsResponse::responses(int index) const {
  // @@protoc_insertion_point(field_get:speechly.slu.v1.TextsResponse.responses)
  return responses_.Get(index);
}
inline ::speechly::slu::v1::WLUResponse* TextsResponse::add_responses() {
  // @@protoc_insertion_point(field_add:speechly.slu.v1.TextsResponse.responses)
  return responses_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLUResponse >&
TextsResponse::responses() const {
  // @@protoc_insertion_point(field_list:speechly.slu.v1.TextsResponse.responses)
  return responses_;
}

// -------------------------------------------------------------------

// WLURequest

// string language_code = 1;
inline void WLURequest::clear_language_code() {
  language_code_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& WLURequest::language_code() const {
  // @@protoc_insertion_point(field_get:speechly.slu.v1.WLURequest.language_code)
  return language_code_.GetNoArena();
}
inline void WLURequest::set_language_code(const std::string& value) {
  
  language_code_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:speechly.slu.v1.WLURequest.language_code)
}
inline void WLURequest::set_language_code(std::string&& value) {
  
  language_code_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:speechly.slu.v1.WLURequest.language_code)
}
inline void WLURequest::set_language_code(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  language_code_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:speechly.slu.v1.WLURequest.language_code)
}
inline void WLURequest::set_language_code(const char* value, size_t size) {
  
  language_code_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:speechly.slu.v1.WLURequest.language_code)
}
inline std::string* WLURequest::mutable_language_code() {
  
  // @@protoc_insertion_point(field_mutable:speechly.slu.v1.WLURequest.language_code)
  return language_code_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* WLURequest::release_language_code() {
  // @@protoc_insertion_point(field_release:speechly.slu.v1.WLURequest.language_code)
  
  return language_code_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void WLURequest::set_allocated_language_code(std::string* language_code) {
  if (language_code != nullptr) {
    
  } else {
    
  }
  language_code_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), language_code);
  // @@protoc_insertion_point(field_set_allocated:speechly.slu.v1.WLURequest.language_code)
}

// string text = 2;
inline void WLURequest::clear_text() {
  text_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& WLURequest::text() const {
  // @@protoc_insertion_point(field_get:speechly.slu.v1.WLURequest.text)
  return text_.GetNoArena();
}
inline void WLURequest::set_text(const std::string& value) {
  
  text_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:speechly.slu.v1.WLURequest.text)
}
inline void WLURequest::set_text(std::string&& value) {
  
  text_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:speechly.slu.v1.WLURequest.text)
}
inline void WLURequest::set_text(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  text_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:speechly.slu.v1.WLURequest.text)
}
inline void WLURequest::set_text(const char* value, size_t size) {
  
  text_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:speechly.slu.v1.WLURequest.text)
}
inline std::string* WLURequest::mutable_text() {
  
  // @@protoc_insertion_point(field_mutable:speechly.slu.v1.WLURequest.text)
  return text_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* WLURequest::release_text() {
  // @@protoc_insertion_point(field_release:speechly.slu.v1.WLURequest.text)
  
  return text_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void WLURequest::set_allocated_text(std::string* text) {
  if (text != nullptr) {
    
  } else {
    
  }
  text_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), text);
  // @@protoc_insertion_point(field_set_allocated:speechly.slu.v1.WLURequest.text)
}

// .google.protobuf.Timestamp reference_time = 3;
inline bool WLURequest::has_reference_time() const {
  return this != internal_default_instance() && reference_time_ != nullptr;
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& WLURequest::reference_time() const {
  const PROTOBUF_NAMESPACE_ID::Timestamp* p = reference_time_;
  // @@protoc_insertion_point(field_get:speechly.slu.v1.WLURequest.reference_time)
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Timestamp*>(
      &PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* WLURequest::release_reference_time() {
  // @@protoc_insertion_point(field_release:speechly.slu.v1.WLURequest.reference_time)
  
  PROTOBUF_NAMESPACE_ID::Timestamp* temp = reference_time_;
  reference_time_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* WLURequest::mutable_reference_time() {
  
  if (reference_time_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Timestamp>(GetArenaNoVirtual());
    reference_time_ = p;
  }
  // @@protoc_insertion_point(field_mutable:speechly.slu.v1.WLURequest.reference_time)
  return reference_time_;
}
inline void WLURequest::set_allocated_reference_time(PROTOBUF_NAMESPACE_ID::Timestamp* reference_time) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(reference_time_);
  }
  if (reference_time) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(reference_time)->GetArena();
    if (message_arena != submessage_arena) {
      reference_time = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, reference_time, submessage_arena);
    }
    
  } else {
    
  }
  reference_time_ = reference_time;
  // @@protoc_insertion_point(field_set_allocated:speechly.slu.v1.WLURequest.reference_time)
}

// -------------------------------------------------------------------

// WLUResponse

// repeated .speechly.slu.v1.WLUSegment segments = 1;
inline int WLUResponse::segments_size() const {
  return segments_.size();
}
inline void WLUResponse::clear_segments() {
  segments_.Clear();
}
inline ::speechly::slu::v1::WLUSegment* WLUResponse::mutable_segments(int index) {
  // @@protoc_insertion_point(field_mutable:speechly.slu.v1.WLUResponse.segments)
  return segments_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLUSegment >*
WLUResponse::mutable_segments() {
  // @@protoc_insertion_point(field_mutable_list:speechly.slu.v1.WLUResponse.segments)
  return &segments_;
}
inline const ::speechly::slu::v1::WLUSegment& WLUResponse::segments(int index) const {
  // @@protoc_insertion_point(field_get:speechly.slu.v1.WLUResponse.segments)
  return segments_.Get(index);
}
inline ::speechly::slu::v1::WLUSegment* WLUResponse::add_segments() {
  // @@protoc_insertion_point(field_add:speechly.slu.v1.WLUResponse.segments)
  return segments_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLUSegment >&
WLUResponse::segments() const {
  // @@protoc_insertion_point(field_list:speechly.slu.v1.WLUResponse.segments)
  return segments_;
}

// -------------------------------------------------------------------

// WLUSegment

// string text = 1;
inline void WLUSegment::clear_text() {
  text_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& WLUSegment::text() const {
  // @@protoc_insertion_point(field_get:speechly.slu.v1.WLUSegment.text)
  return text_.GetNoArena();
}
inline void WLUSegment::set_text(const std::string& value) {
  
  text_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:speechly.slu.v1.WLUSegment.text)
}
inline void WLUSegment::set_text(std::string&& value) {
  
  text_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:speechly.slu.v1.WLUSegment.text)
}
inline void WLUSegment::set_text(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  text_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:speechly.slu.v1.WLUSegment.text)
}
inline void WLUSegment::set_text(const char* value, size_t size) {
  
  text_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:speechly.slu.v1.WLUSegment.text)
}
inline std::string* WLUSegment::mutable_text() {
  
  // @@protoc_insertion_point(field_mutable:speechly.slu.v1.WLUSegment.text)
  return text_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* WLUSegment::release_text() {
  // @@protoc_insertion_point(field_release:speechly.slu.v1.WLUSegment.text)
  
  return text_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void WLUSegment::set_allocated_text(std::string* text) {
  if (text != nullptr) {
    
  } else {
    
  }
  text_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), text);
  // @@protoc_insertion_point(field_set_allocated:speechly.slu.v1.WLUSegment.text)
}

// repeated .speechly.slu.v1.WLUToken tokens = 2;
inline int WLUSegment::tokens_size() const {
  return tokens_.size();
}
inline void WLUSegment::clear_tokens() {
  tokens_.Clear();
}
inline ::speechly::slu::v1::WLUToken* WLUSegment::mutable_tokens(int index) {
  // @@protoc_insertion_point(field_mutable:speechly.slu.v1.WLUSegment.tokens)
  return tokens_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLUToken >*
WLUSegment::mutable_tokens() {
  // @@protoc_insertion_point(field_mutable_list:speechly.slu.v1.WLUSegment.tokens)
  return &tokens_;
}
inline const ::speechly::slu::v1::WLUToken& WLUSegment::tokens(int index) const {
  // @@protoc_insertion_point(field_get:speechly.slu.v1.WLUSegment.tokens)
  return tokens_.Get(index);
}
inline ::speechly::slu::v1::WLUToken* WLUSegment::add_tokens() {
  // @@protoc_insertion_point(field_add:speechly.slu.v1.WLUSegment.tokens)
  return tokens_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLUToken >&
WLUSegment::tokens() const {
  // @@protoc_insertion_point(field_list:speechly.slu.v1.WLUSegment.tokens)
  return tokens_;
}

// repeated .speechly.slu.v1.WLUEntity entities = 3;
inline int WLUSegment::entities_size() const {
  return entities_.size();
}
inline void WLUSegment::clear_entities() {
  entities_.Clear();
}
inline ::speechly::slu::v1::WLUEntity* WLUSegment::mutable_entities(int index) {
  // @@protoc_insertion_point(field_mutable:speechly.slu.v1.WLUSegment.entities)
  return entities_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLUEntity >*
WLUSegment::mutable_entities() {
  // @@protoc_insertion_point(field_mutable_list:speechly.slu.v1.WLUSegment.entities)
  return &entities_;
}
inline const ::speechly::slu::v1::WLUEntity& WLUSegment::entities(int index) const {
  // @@protoc_insertion_point(field_get:speechly.slu.v1.WLUSegment.entities)
  return entities_.Get(index);
}
inline ::speechly::slu::v1::WLUEntity* WLUSegment::add_entities() {
  // @@protoc_insertion_point(field_add:speechly.slu.v1.WLUSegment.entities)
  return entities_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::speechly::slu::v1::WLUEntity >&
WLUSegment::entities() const {
  // @@protoc_insertion_point(field_list:speechly.slu.v1.WLUSegment.entities)
  return entities_;
}

// .speechly.slu.v1.WLUIntent intent = 4;
inline bool WLUSegment::has_intent() const {
  return this != internal_default_instance() && intent_ != nullptr;
}
inline void WLUSegment::clear_intent() {
  if (GetArenaNoVirtual() == nullptr && intent_ != nullptr) {
    delete intent_;
  }
  intent_ = nullptr;
}
inline const ::speechly::slu::v1::WLUIntent& WLUSegment::intent() const {
  const ::speechly::slu::v1::WLUIntent* p = intent_;
  // @@protoc_insertion_point(field_get:speechly.slu.v1.WLUSegment.intent)
  return p != nullptr ? *p : *reinterpret_cast<const ::speechly::slu::v1::WLUIntent*>(
      &::speechly::slu::v1::_WLUIntent_default_instance_);
}
inline ::speechly::slu::v1::WLUIntent* WLUSegment::release_intent() {
  // @@protoc_insertion_point(field_release:speechly.slu.v1.WLUSegment.intent)
  
  ::speechly::slu::v1::WLUIntent* temp = intent_;
  intent_ = nullptr;
  return temp;
}
inline ::speechly::slu::v1::WLUIntent* WLUSegment::mutable_intent() {
  
  if (intent_ == nullptr) {
    auto* p = CreateMaybeMessage<::speechly::slu::v1::WLUIntent>(GetArenaNoVirtual());
    intent_ = p;
  }
  // @@protoc_insertion_point(field_mutable:speechly.slu.v1.WLUSegment.intent)
  return intent_;
}
inline void WLUSegment::set_allocated_intent(::speechly::slu::v1::WLUIntent* intent) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete intent_;
  }
  if (intent) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      intent = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, intent, submessage_arena);
    }
    
  } else {
    
  }
  intent_ = intent;
  // @@protoc_insertion_point(field_set_allocated:speechly.slu.v1.WLUSegment.intent)
}

// string annotated_text = 5;
inline void WLUSegment::clear_annotated_text() {
  annotated_text_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& WLUSegment::annotated_text() const {
  // @@protoc_insertion_point(field_get:speechly.slu.v1.WLUSegment.annotated_text)
  return annotated_text_.GetNoArena();
}
inline void WLUSegment::set_annotated_text(const std::string& value) {
  
  annotated_text_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:speechly.slu.v1.WLUSegment.annotated_text)
}
inline void WLUSegment::set_annotated_text(std::string&& value) {
  
  annotated_text_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:speechly.slu.v1.WLUSegment.annotated_text)
}
inline void WLUSegment::set_annotated_text(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  annotated_text_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:speechly.slu.v1.WLUSegment.annotated_text)
}
inline void WLUSegment::set_annotated_text(const char* value, size_t size) {
  
  annotated_text_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:speechly.slu.v1.WLUSegment.annotated_text)
}
inline std::string* WLUSegment::mutable_annotated_text() {
  
  // @@protoc_insertion_point(field_mutable:speechly.slu.v1.WLUSegment.annotated_text)
  return annotated_text_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* WLUSegment::release_annotated_text() {
  // @@protoc_insertion_point(field_release:speechly.slu.v1.WLUSegment.annotated_text)
  
  return annotated_text_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void WLUSegment::set_allocated_annotated_text(std::string* annotated_text) {
  if (annotated_text != nullptr) {
    
  } else {
    
  }
  annotated_text_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), annotated_text);
  // @@protoc_insertion_point(field_set_allocated:speechly.slu.v1.WLUSegment.annotated_text)
}

// -------------------------------------------------------------------

// WLUToken

// string word = 1;
inline void WLUToken::clear_word() {
  word_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& WLUToken::word() const {
  // @@protoc_insertion_point(field_get:speechly.slu.v1.WLUToken.word)
  return word_.GetNoArena();
}
inline void WLUToken::set_word(const std::string& value) {
  
  word_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:speechly.slu.v1.WLUToken.word)
}
inline void WLUToken::set_word(std::string&& value) {
  
  word_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:speechly.slu.v1.WLUToken.word)
}
inline void WLUToken::set_word(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  word_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:speechly.slu.v1.WLUToken.word)
}
inline void WLUToken::set_word(const char* value, size_t size) {
  
  word_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:speechly.slu.v1.WLUToken.word)
}
inline std::string* WLUToken::mutable_word() {
  
  // @@protoc_insertion_point(field_mutable:speechly.slu.v1.WLUToken.word)
  return word_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* WLUToken::release_word() {
  // @@protoc_insertion_point(field_release:speechly.slu.v1.WLUToken.word)
  
  return word_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void WLUToken::set_allocated_word(std::string* word) {
  if (word != nullptr) {
    
  } else {
    
  }
  word_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), word);
  // @@protoc_insertion_point(field_set_allocated:speechly.slu.v1.WLUToken.word)
}

// int32 index = 2;
inline void WLUToken::clear_index() {
  index_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 WLUToken::index() const {
  // @@protoc_insertion_point(field_get:speechly.slu.v1.WLUToken.index)
  return index_;
}
inline void WLUToken::set_index(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  index_ = value;
  // @@protoc_insertion_point(field_set:speechly.slu.v1.WLUToken.index)
}

// -------------------------------------------------------------------

// WLUEntity

// string entity = 1;
inline void WLUEntity::clear_entity() {
  entity_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& WLUEntity::entity() const {
  // @@protoc_insertion_point(field_get:speechly.slu.v1.WLUEntity.entity)
  return entity_.GetNoArena();
}
inline void WLUEntity::set_entity(const std::string& value) {
  
  entity_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:speechly.slu.v1.WLUEntity.entity)
}
inline void WLUEntity::set_entity(std::string&& value) {
  
  entity_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:speechly.slu.v1.WLUEntity.entity)
}
inline void WLUEntity::set_entity(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  entity_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:speechly.slu.v1.WLUEntity.entity)
}
inline void WLUEntity::set_entity(const char* value, size_t size) {
  
  entity_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:speechly.slu.v1.WLUEntity.entity)
}
inline std::string* WLUEntity::mutable_entity() {
  
  // @@protoc_insertion_point(field_mutable:speechly.slu.v1.WLUEntity.entity)
  return entity_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* WLUEntity::release_entity() {
  // @@protoc_insertion_point(field_release:speechly.slu.v1.WLUEntity.entity)
  
  return entity_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void WLUEntity::set_allocated_entity(std::string* entity) {
  if (entity != nullptr) {
    
  } else {
    
  }
  entity_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), entity);
  // @@protoc_insertion_point(field_set_allocated:speechly.slu.v1.WLUEntity.entity)
}

// string value = 2;
inline void WLUEntity::clear_value() {
  value_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& WLUEntity::value() const {
  // @@protoc_insertion_point(field_get:speechly.slu.v1.WLUEntity.value)
  return value_.GetNoArena();
}
inline void WLUEntity::set_value(const std::string& value) {
  
  value_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:speechly.slu.v1.WLUEntity.value)
}
inline void WLUEntity::set_value(std::string&& value) {
  
  value_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:speechly.slu.v1.WLUEntity.value)
}
inline void WLUEntity::set_value(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  value_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:speechly.slu.v1.WLUEntity.value)
}
inline void WLUEntity::set_value(const char* value, size_t size) {
  
  value_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:speechly.slu.v1.WLUEntity.value)
}
inline std::string* WLUEntity::mutable_value() {
  
  // @@protoc_insertion_point(field_mutable:speechly.slu.v1.WLUEntity.value)
  return value_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* WLUEntity::release_value() {
  // @@protoc_insertion_point(field_release:speechly.slu.v1.WLUEntity.value)
  
  return value_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void WLUEntity::set_allocated_value(std::string* value) {
  if (value != nullptr) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:speechly.slu.v1.WLUEntity.value)
}

// int32 start_position = 3;
inline void WLUEntity::clear_start_position() {
  start_position_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 WLUEntity::start_position() const {
  // @@protoc_insertion_point(field_get:speechly.slu.v1.WLUEntity.start_position)
  return start_position_;
}
inline void WLUEntity::set_start_position(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  start_position_ = value;
  // @@protoc_insertion_point(field_set:speechly.slu.v1.WLUEntity.start_position)
}

// int32 end_position = 4;
inline void WLUEntity::clear_end_position() {
  end_position_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 WLUEntity::end_position() const {
  // @@protoc_insertion_point(field_get:speechly.slu.v1.WLUEntity.end_position)
  return end_position_;
}
inline void WLUEntity::set_end_position(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  end_position_ = value;
  // @@protoc_insertion_point(field_set:speechly.slu.v1.WLUEntity.end_position)
}

// -------------------------------------------------------------------

// WLUIntent

// string intent = 1;
inline void WLUIntent::clear_intent() {
  intent_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& WLUIntent::intent() const {
  // @@protoc_insertion_point(field_get:speechly.slu.v1.WLUIntent.intent)
  return intent_.GetNoArena();
}
inline void WLUIntent::set_intent(const std::string& value) {
  
  intent_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:speechly.slu.v1.WLUIntent.intent)
}
inline void WLUIntent::set_intent(std::string&& value) {
  
  intent_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:speechly.slu.v1.WLUIntent.intent)
}
inline void WLUIntent::set_intent(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  intent_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:speechly.slu.v1.WLUIntent.intent)
}
inline void WLUIntent::set_intent(const char* value, size_t size) {
  
  intent_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:speechly.slu.v1.WLUIntent.intent)
}
inline std::string* WLUIntent::mutable_intent() {
  
  // @@protoc_insertion_point(field_mutable:speechly.slu.v1.WLUIntent.intent)
  return intent_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* WLUIntent::release_intent() {
  // @@protoc_insertion_point(field_release:speechly.slu.v1.WLUIntent.intent)
  
  return intent_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void WLUIntent::set_allocated_intent(std::string* intent) {
  if (intent != nullptr) {
    
  } else {
    
  }
  intent_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), intent);
  // @@protoc_insertion_point(field_set_allocated:speechly.slu.v1.WLUIntent.intent)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace slu
}  // namespace speechly

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_speechly_2fslu_2fv1_2fwlu_2eproto
